"use client";

import Image from "next/image";
import { motion } from "framer-motion";
import { Sun, Zap, Home, Building2, Building } from "lucide-react";

export default function OnGridSolar() {
    return (
        <section className="min-h-screen bg-gradient-to-b from-[#FDF9F3] to-[#F9F5EC] py-16">
            <div className="container mx-auto px-6 lg:px-16">
                {/* Hero Section */}
                <div className="grid md:grid-cols-2 gap-12 items-center">
                    {/* Image */}
                    <motion.div
                        initial={{ opacity: 0, x: -50 }}
                        animate={{ opacity: 1, x: 0 }}
                        transition={{ duration: 0.8 }}
                    >
                        <Image
                            src="/Projects/7.jpg"
                            alt="On Grid Solar System"
                            width={600}
                            height={400}
                            className="rounded-2xl shadow-lg border-4 border-[#C5A352]/30"
                        />
                    </motion.div>

                    {/* Text */}
                    <motion.div
                        initial={{ opacity: 0, x: 50 }}
                        animate={{ opacity: 1, x: 0 }}
                        transition={{ duration: 0.8 }}
                    >
                        <h1 className="text-4xl md:text-5xl font-extrabold text-[#3B0A4F] mb-6">
                            On-Grid Solar System
                        </h1>
                        <p className="text-gray-700 leading-relaxed text-lg">
                            A solar on-grid system (also known as a grid-tied solar system) is a
                            solar power setup that is connected to the local electricity grid.
                            It allows you to generate your own solar power while still being able
                            to draw electricity from the grid when needed. Any excess power
                            generated by the solar panels is sent back to the grid, often earning
                            you credits or reducing your electricity bill through net metering.
                        </p>
                    </motion.div>
                </div>

                {/* Main Components */}
                <motion.div
                    initial={{ opacity: 0, y: 50 }}
                    whileInView={{ opacity: 1, y: 0 }}
                    transition={{ duration: 0.8 }}
                    viewport={{ once: true }}
                    className="mt-20"
                >
                    <h2 className="text-3xl font-bold text-[#3B0A4F] mb-8 text-center">
                        Main Components
                    </h2>
                    <div className="grid md:grid-cols-3 gap-8">
                        {[
                            {
                                icon: <Sun className="w-10 h-10 text-[#C5A352]" />,
                                title: "Solar Panels",
                                desc: "Generate electricity from sunlight.",
                            },
                            {
                                icon: <Zap className="w-10 h-10 text-[#C5A352]" />,
                                title: "Grid-tie Inverter",
                                desc: "Converts DC to AC and synchronizes with the grid.",
                            },
                            {
                                icon: <Building className="w-10 h-10 text-[#3B0A4F]" />,
                                title: "Housing Societies & Apartments",
                                desc: "Enables shared solar energy, reducing overall costs.",
                            }


                        ].map((item, i) => (
                            <div
                                key={i}
                                className="bg-white rounded-xl shadow-md p-6 border border-gray-100 hover:shadow-xl hover:-translate-y-1 transition"
                            >
                                <div className="mb-4">{item.icon}</div>
                                <h3 className="font-semibold text-lg text-[#3B0A4F]">
                                    {item.title}
                                </h3>
                                <p className="text-gray-600 mt-2">{item.desc}</p>
                            </div>
                        ))}
                    </div>
                </motion.div>

                {/* Applications */}
                <motion.div
                    initial={{ opacity: 0, y: 50 }}
                    whileInView={{ opacity: 1, y: 0 }}
                    transition={{ duration: 0.8, delay: 0.2 }}
                    viewport={{ once: true }}
                    className="mt-20"
                >
                    <h2 className="text-3xl font-bold text-[#3B0A4F] mb-8 text-center">
                        Applications
                    </h2>
                    <div className="grid md:grid-cols-3 gap-8">
                        {[
                            {
                                icon: <Home className="w-10 h-10 text-[#3B0A4F]" />,
                                title: "Residential Homes",
                                desc: "Provides clean energy, reducing dependence on grid electricity.",
                            },
                            {
                                icon: <Building2 className="w-10 h-10 text-[#3B0A4F]" />,
                                title: "Commercial & Industrial Units",
                                desc: "Helps businesses lower operational costs and improve sustainability.",
                            },
                            {
                                icon: <Building className="w-10 h-10 text-[#3B0A4F]" />,
                                title: "Housing Societies & Apartments",
                                desc: "Enables shared solar energy, reducing overall costs.",
                            }

                        ].map((item, i) => (
                            <div
                                key={i}
                                className="bg-gradient-to-r from-[#C5A352]/20 to-[#E5C97B]/30 rounded-xl shadow-md p-6 hover:shadow-xl hover:-translate-y-1 transition"
                            >
                                <div className="mb-4">{item.icon}</div>
                                <h3 className="font-semibold text-lg text-[#3B0A4F]">
                                    {item.title}
                                </h3>
                                <p className="text-gray-700 mt-2">{item.desc}</p>
                            </div>
                        ))}
                    </div>
                </motion.div>
            </div>
        </section>
    );
}
